Portfolio: setup and mobile first
As1imwe-Mark/Portifolio_toolbar_and_headline_section pull request #1
Opened 2023-05-30 19:58 UTC by As1imwe-Mark

General requirements
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
Linter should be set up correctly for this repository.
Linter result should be green.
There should be no custom changes to linter config.
Make sure that you used correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):
README file should be descriptive.
Commit messages should be meaningful.
Pull Request should have a descriptive title explaining what changes are inside.
Pull Request should have a short summary describing introduced changes in more detail.
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md):
Branch name should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
Pull Request is made from 'feature branch' into the main branch.
HTML/CSS requirements
Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

In order to lay out the elements on the page you should use flexbox in all 2 sections.
Only use HTML & CSS (no JavaScript needed)
Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
Implement the button interactions (i.e. hover, etc.).
The website should be responsive, following these breakpoints:
Minimum mobile screen size should be 375px
Minimum desktop screen size should be 768px
Use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels

2023-05-30 23:22 UTC, Kossi-stack requested changes
## Hi @As1imwe-Mark,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-30 23:22 UTC, Kossi-stack commented on index.html
> +           <a  class="menu-icon" href="#"><img src="./Icons/menu.png" alt=""></a>
- [ ] Kindly use the nav tag for the hamburger. The nav tag is for semantics reasons and the right position for convention and user experience for mobile devices.

2023-05-30 23:22 UTC, Kossi-stack commented on index.html
> +            <div class="twitter-icon"><a href=""><img src="Icons/twitter.png" alt="twitter"></a></div>
- [ ] Kindly make the list of icons use a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).
- Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-05-30 23:22 UTC, Kossi-stack commented on README.md
> +- GitHub: @As1imwe-Mark
- [ ] Kindly make sure your social handle are links that you can click. @githubhandle can be your name
- see the example below
<img width="731" alt="Screenshot 2023-05-30 at 16 17 59" src="https://github.com/As1imwe-Mark/Portifolio_toolbar_and_headline_section/assets/81444338/9bade111-9a6c-48ad-ad57-f425bd4f7635">

2023-05-31 00:12 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @As1imwe-Mark 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 00:12 UTC, tresorsawasawa commented on index.html
> +            <li class="linkedin-icon"><a href=""><img src="Icons/linkedin.png" alt="linkedin"></span></a></li>
- [ **OPTIONAL** ] **RECOMMENDED:** I think it would be better if you remove the non-used closing `</span>` tag tag from this line to make your code base be more professional

2023-05-31 00:12 UTC, tresorsawasawa commented on README.md
> +-->
- [ **OPTIONAL** ] **RECOMMENDED:** As mentioned in the template and for clean code reasons, I think it would be better if you remove all the comments and instructions from your README code after you have finished to use it.

2023-05-31 00:12 UTC, tresorsawasawa commented on README.md
> +
- [ ] Good job trying to fix some of changes mentioned by the previous reviewer. However I noticed that you didn't apply this apprach to all your social usernames if you have accounts, I recommend to do it for all of them. This will make your documentation be more professional and you should ensure that all the provided links are working. For example:
```
....
- LinkedIn: [AsiimweMark](https://www.linkedin.com/in/your_linkedin_username)
- Twitter: [@markasiimwe](https://twitter.com/your_twitter_username)
...
```

2023-05-31 00:54 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @As1imwe-Mark, 

<img height="220" src="https://media4.giphy.com/media/Cm9wKmKMUlRPvdoHgU/giphy-downsized-medium.gif"/>


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Good commit messages 👍 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 01:00 UTC, merged